In [ ]:
# GROUP MEMBERS
# UROOSA ASIM (FA18-BSCS-0084)
# ASMA LATIF (FA18-BSCS-0131)

# MACHINE LEARNING ALGORITHMS

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
#read the datasets
train = pd.read_csv("E:/Data Set/train.csv")
test = pd.read_csv("E:/Data Set/test.csv")

In [ ]:
target = pd.read_csv("C:\\Users\\Uroosa Asim\\Downloads\\sample_submission.csv")

In [ ]:
target.head()

id  Response
0  381110         0
1  381111         0
2  381112         0
3  381113         0
4  381114         0

In [ ]:
encoder= LabelEncoder()
test["Gender"]=encoder.fit_transform(test["Gender"])
test["Vehicle_Age"]=encoder.fit_transform(test["Vehicle_Age"])
test["Vehicle_Damage"]=encoder.fit_transform(test["Vehicle_Damage"])

In [ ]:
test["Vehicle_Age"].unique()

array([1, 0, 2])

In [ ]:
test['Vehicle_Damage'].unique()

array([0, 1])

In [ ]:
test_df=test[["Gender","Vehicle_Age","Vehicle_Damage","Age","Driving_License","Region_Code","Previously_Insured","Policy_Sales_Channel","Vintage"]]

In [ ]:
encoder= LabelEncoder()
train["Gender"]=encoder.fit_transform(train["Gender"])
train["Vehicle_Age"]=encoder.fit_transform(train["Vehicle_Age"])
train["Vehicle_Damage"]=encoder.fit_transform(train["Vehicle_Damage"])

In [ ]:
train_df=train[["Gender","Vehicle_Age","Vehicle_Damage","Age","Driving_License","Region_Code","Previously_Insured","Policy_Sales_Channel","Vintage","Response"]]

In [ ]:
correlated_features = set()
correlation_matrix = train_df.corr()
correlation_matrix

Gender  Vehicle_Age  Vehicle_Damage       Age  \
Gender                1.000000    -0.112625        0.091606  0.145545   
Vehicle_Age          -0.112625     1.000000       -0.174238 -0.522300   
Vehicle_Damage        0.091606    -0.174238        1.000000  0.267534   
Age                   0.145545    -0.522300        0.267534  1.000000   
Driving_License      -0.018374     0.030173       -0.016622 -0.079782   
Region_Code           0.000604    -0.027840        0.028235  0.042574   
Previously_Insured   -0.081932     0.174783       -0.824143 -0.254682   
Policy_Sales_Channel -0.111159     0.388551       -0.224377 -0.577826   
Vintage              -0.002517     0.002484       -0.002064 -0.001264   
Response              0.052440    -0.104078        0.354400  0.111147   

                      Driving_License  Region_Code  Previously_Insured  \
Gender                      -0.018374     0.000604           -0.081932   
Vehicle_Age                  0.030173    -0.027840            0.174783   
Vehicle_Damage              -0.016622     0.028235           -0.824143   
Age                         -0.079782     0.042574           -0.254682   
Driving_License              1.000000    -0.001081            0.014969   
Region_Code                 -0.001081     1.000000           -0.024659   
Previously_Insured           0.014969    -0.024659            1.000000   
Policy_Sales_Channel         0.043731    -0.042420            0.219381   
Vintage                     -0.000848    -0.002750            0.002537   
Response                     0.010155     0.010570           -0.341170   

                      Policy_Sales_Channel   Vintage  Response  
Gender                           -0.111159 -0.002517  0.052440  
Vehicle_Age                       0.388551  0.002484 -0.104078  
Vehicle_Damage                   -0.224377 -0.002064  0.354400  
Age                              -0.577826 -0.001264  0.111147  
Driving_License                   0.043731 -0.000848  0.010155  
Region_Code                      -0.042420 -0.002750  0.010570  
Previously_Insured                0.219381  0.002537 -0.341170  
Policy_Sales_Channel              1.000000  0.000002 -0.139042  
Vintage                           0.000002  1.000000 -0.001050  
Response                         -0.139042 -0.001050  1.000000

In [ ]:
for i in range(len(correlation_matrix.columns)):
    for j in range(i):
        if abs(correlation_matrix.iloc[i, j]) > 0.8:
            colname = correlation_matrix.columns[i]
            correlated_features.add(colname)

train_df.drop(columns=correlated_features)

Gender  Vehicle_Age  Vehicle_Damage  Age  Driving_License  \
0            1            2               1   44                1   
1            1            0               0   76                1   
2            1            2               1   47                1   
3            1            1               0   21                1   
4            0            1               0   29                1   
...        ...          ...             ...  ...              ...   
381104       1            0               0   74                1   
381105       1            1               0   30                1   
381106       1            1               0   21                1   
381107       0            2               1   68                1   
381108       1            0               0   46                1   

        Region_Code  Policy_Sales_Channel  Vintage  Response  
0              28.0                  26.0      217         1  
1               3.0                  26.0      183         0  
2              28.0                  26.0       27         1  
3              11.0                 152.0      203         0  
4              41.0                 152.0       39         0  
...             ...                   ...      ...       ...  
381104         26.0                  26.0       88         0  
381105         37.0                 152.0      131         0  
381106         30.0                 160.0      161         0  
381107         14.0                 124.0       74         0  
381108         29.0                  26.0      237         0  

[381109 rows x 9 columns]

In [ ]:
X_train = train_df.drop('Response', axis=1)
y_train = train_df['Response']
y_train=y_train.astype(int)

# LOGISTIC REGRESSION

In [ ]:
logReg=LogisticRegression(solver='lbfgs')
rfe = RFE(logReg, 20)
rfe = rfe.fit(X_train, y_train.values.ravel())
#Checking for the features are they important
print(rfe.support_)

E:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:68: FutureWarning: Pass n_features_to_select=20 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


[ True  True  True  True  True  True  True  True  True]


E:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
y_test=target['Response']

In [ ]:
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred = logreg.predict(test_df)
print(confusion_matrix(y_test,y_pred))
print('Accuracy of logistic regression classifier on train set: {:.4f}'.format(logreg.score(X_train, y_train)))
print('Accuracy of logistic regression classifier on test set: {:.4f}'.format(logreg.score(test_df, y_test)))

E:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[126936    101]
 [     0      0]]
Accuracy of logistic regression classifier on train set: 0.8766
Accuracy of logistic regression classifier on test set: 0.9992


# DECISION TREE ALGORITHM

In [ ]:
dtree=DecisionTreeClassifier()
dtree.fit(X_train,y_train)
dtree.score(test_df,y_test)
y_pred = dtree.predict(test_df)
print(confusion_matrix(y_test,y_pred))
print('Accuracy of decision tree classifier on train set: {:.4f}'.format(dtree.score(X_train, y_train)))
print('Accuracy of decision tree classifier on test set: {:.4f}'.format(dtree.score(test_df, y_test)))

[[111945  15092]
 [     0      0]]
Accuracy of decision tree classifier on train set: 0.9832
Accuracy of decision tree classifier on test set: 0.8812
